Gem::Specification.new do |s|
  s.name         = 'prop_check'
  s.version      = '0.5.0'
  s.date         = '2019-06-21'
  s.summary      = "Property Checking library: Run your tests repeatedly with autogenerated inputs. (Akin Haskell's QuickCheck / Erlang's PropEr)"
  s.description  = "Property Checking library: Run your tests repeatedly with autogenerated inputs. (Akin Haskell's QuickCheck / Erlang's PropEr)"
  s.authors      = ["Wiebe Marten Wijnja / Qqwy"]
  s.files        = Dir['README.md', 'VERSION', 'Gemfile', 'Rakefile', '{bin,lib,config,vendor}/**/*']
  s.require_path = 'lib'
  s.homepage     = 'https://github.com/Qqwy/ruby_property_checking'
  s.email        = 'w-m@wmcode.nl'
  s.license      = 'MIT'
end
